// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUoDezzPpe4ued3cq8l7WKokncEaTaSms',
    appId: '1:994630950681:web:29562f4003b5f046852f88',
    messagingSenderId: '994630950681',
    projectId: 'fireblog-64987',
    authDomain: 'fireblog-64987.firebaseapp.com',
    storageBucket: 'fireblog-64987.appspot.com',
    measurementId: 'G-4D5PMC921Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuXLnpvFjRusBSkMUo2j7ont7BvFzJJ64',
    appId: '1:994630950681:android:2eff6bcaa3c4bd96852f88',
    messagingSenderId: '994630950681',
    projectId: 'fireblog-64987',
    storageBucket: 'fireblog-64987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCEPxfZq7aBYGMhClTRdpqeGyun3bWtkE',
    appId: '1:994630950681:ios:0061f92a6dabc1d6852f88',
    messagingSenderId: '994630950681',
    projectId: 'fireblog-64987',
    storageBucket: 'fireblog-64987.appspot.com',
    iosBundleId: 'com.cybrnode.fireblog',
  );
}
